server:
  port: 80
  tomcat:
    accept-count: 1000
    max-threads: 200
    max-connections: 2000
    min-spare-threads: 10
spring:
  application:
    name: mock
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  main:
    allow-bean-definition-overriding: true